---

- import_tasks: setup-pip-Linux.yml
  when: ansible_system == 'Linux'

- import_tasks: setup-pip-Darwin.yml
  when: ansible_system == 'Darwin'

- name: Set Certbot script variable.
  set_fact:
    certbot_script: '/usr/local/bin/certbot'