---

- import_tasks: setup-pip-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: setup-pip-Darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Set Certbot script variable.
  set_fact:
    certbot_script: '/usr/local/bin/certbot'
