---
- name: Pre-create certbot virtualenv directory
  file:
    path: "{{ certbot_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ certbot_group }}"
    mode: 755
  become: true

- name: Install pip dependencies for MacOS
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
  - python3
  - virtualenv

- name: Install certbot via pip
  pip:
    name:
    - certbot
    - certbot-dns-cloudflare
    virtualenv: "{{ certbot_dir }}"
    virtualenv_python: "{{ certbot_python3_binary }}"
    state: present

- name: Ensure configuration directory exists
  file:
    path: "{{ certbot_cli_conf_dir }}"
    state: directory
    mode: 0755

- name: Copy certbot cli.ini for MacOS
  template:
    src: cli.ini.j2
    dest: "{{ certbot_cli_conf_dir }}/cli.ini"
    mode: 0644

- name: Symlink certbot into place.
  file:
    src: "{{ certbot_dir }}/bin/certbot"
    dest: /usr/local/bin/certbot
    state: link
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
