---
- name: Install dependencies for Debian based systems
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-venv
    - python3-pip
    - virtualenv
  when: ansible_os_family == Debian

- name: Install dependencies for Redhat based systems
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-virtualenv
    - python3-pip
  when: ansible_os_family == Redhat
  
- name: Install certbot via pip
  pip:
    name:
      - certbot
      - certbot-dns-cloudflare
    virtualenv: "{{ certbot_dir }}"
    virtualenv_python: "{{ certbot_python3_binary }}"
    state: present

- name: Symlink certbot into place.
  file:
    src: "{{ certbot_dir }}/bin/certbot"
    dest: /usr/local/bin/certbot
    state: link
  ignore_errors: "{{ ansible_check_mode }}"